### ISSUE TITLE
Inconsistent payload 

### ISSUE THREAD

**Issue by kiteloop** [samj1912/fbrecog#5]
I have the problem that sometimes I never get a payload back.
Has anyone seen similar issues?
Is there some sort of rate limit of the API? It usually works fine for a couple of requests and then I'm unable to get any payload after that.

**Comment by sambhav** [comment]
Yeah, fb rate limits the end point. That is why there is a while loop to request the payload.

**Comment by SamaraRen** [comment]
@samj1912 Hi, I wasn't able to get any response back, instead, the following error message was returned:  in recognize for recog in payload[0]['faceboxes']: KeyError: 0
Is this also part of the rate limit?
Thanks!
